services:
  inventory_postgres:
    container_name: inventory_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - inventory_postgres:/var/lib/postgresql/data
    ports:
      - 5532:5432
    networks:
      - microservices-net
    restart: unless-stopped

  order_postgres:
    container_name: order_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - order_postgres:/var/lib/postgresql/data
    ports:
      - 5632:5432
    networks:
      - microservices-net
    restart: unless-stopped

  payment_postgres:
    container_name: payment_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - payment_postgres:/var/lib/postgresql/data
    ports:
      - 5732:5432
    networks:
      - microservices-net
    restart: unless-stopped

  user_mongodb:
    container_name: user_mongo_db
    image: mongo
    ports:
      - 28017:27017
    volumes:
      - user_mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  catalog_mongodb:
    container_name: catalog_mongo_db
    image: mongo
    ports:
      - 29017:27017
    volumes:
      - catalog_mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  notification_mongodb:
    container_name: notification_mongo_db
    image: mongo
    ports:
      - 30017:27017
    volumes:
      - notification_mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mail-dev:
    container_name: ms_email_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  inventory_postgres:
  order_postgres:
  payment_postgres:
  user_mongo:
  catalog_mongo:
  notification_mongo: